
services:
  python-app:
    build:
      context: ./app/lab-03-starter-project-python
    container_name: python-app
    ports:
      - "8081:8080"
    volumes:
      - ./app/lab-03-starter-project-python:/app
    restart: unless-stopped

  go-app:
    build:
      context: ./app/lab-03-starter-project-golang
      dockerfile: Dockerfile
    container_name: go-app
    volumes:
         - ./app/lab-03-starter-project-golang:/app
    ports:
      - "8082:8080"
    restart: unless-stopped

